---
url: ftp.fec.gov
db:
  dbname: DB_NAME
  dblogin: DB_LOGIN
  dbpass: DB_PASS
:col_types:
  :date: _date
  :integer: filing_id
  :float: cash|amount|contributions|total|loan|transfer|debts|refund|expenditure
tables:
  individual:
    - category: summary
      table: IndividualContributions
      description: Political contributions made out to PACs from individuals
      fec_file: indiv
      headers:
        - committee_id
        - amendment_indicator
        - report_type
        - election_type
        - image_number
        - trans_type
        - entity_type
        - name
        - city
        - state
        - zip
        - employer
        - occupation
        - trans_date
        - trans_amount
        - other_id
        - trans_id
        - filing_id
        - memo_cd
        - memo_txt
        - fec_record_number
  committee:
    - category: summary
      table: CommitteeSummary
      description: Summary of all contributions made to a particular committee within an election cycle
      fec_file: webk
      headers:
        - committee_id
        - committee_name
        - type
        - designation
        - filing_frequency
        - total_receipts
        - transfers_from_affiliates
        - individual_contributions
        - pac_contributions
        - candidate_contributions
        - candidate_loans
        - total_loans_received
        - total_disbursements
        - transfers_to_affiliates
        - individual_refunds
        - committee_refunds
        - candidate_loan_repayments
        - loan_repayments
        - beginning_year_cash
        - ending_cash
        - debts_owed_by
        - nonfederal_transfers_received
        - contributions_to_committees
        - independent_expenditures
        - party_coordinated_expenditures
        - nonfederal_share_expenditures
        - coverage_end_date
    - category: link
      table: CommitteeLink
      fec_file: ccl
      description: Committee's with established links with candidates.
      headers:
        - committee_id
        - candidate_election_year
        - election_year
        - candidate_id
        - type
        - designation
          - linkage_id
    - category: detail
      table: CommitteeDetail
      fec_file: cm
      headers:
        - committee_id
        - committee_name
        - treasurer
        - street_one
        - street_two
        - city
        - state
        - zipcode
        - designation
        - type
        - party
        - filing_frequency
        - category
        - connected_organization
        - candidate_id
  candidate:
    - category: contribution
      table: CandidateContribution
      fec_file: oth
      headers:
        - committee_id
        - amendment
        - report_type
        - primary_general
        - microfilm
        - transaction_type
        - entity_type
        - name
        - city
        - state
        - zipcode
        - employer
        - occupation
        - transaction_date
        - amount
        - other_committee_id
        - candidate_id
        - transaction_id
        - filing_id
        - memo_code
        - memo_text
        - fec_record_number
    - category: summary
      table: CandidateSummary
      fec_file: webl
      headers:
        - candidate_id
        - candidate_name
        - status
        - party_code
        - party
        - total_receipts
        - transfers_from_authorized
        - total_disbursements
        - transfers_to_authorized
        - beginning_cash
        - ending_cash
        - candidate_contributions
        - candidate_loans
        - other_loans
        - candidate_loan_repayments
        - other_loan_repayments
        - debts_owed_by
        - total_individual_contributions
        - office_state
        - district
        - special_election_status
        - primary_election_status
        - runoff_election_status
        - general_election_status
        - general_election_percent
        - pac_contributions
        - party_contributions
        - coverage_end_date
        - individual_refunds
        - committee_refunds
    - category: current
      table: CandidateCurrent
      fec_file: weball
      headers:
        - candidate_id
        - candidate_name
        - status
        - party_code
        - party
        - total_receipts
        - transfers_from_authorized
        - total_disbursements
        - transfers_to_authorized
        - beginning_cash
        - ending_cash
        - candidate_contributions
        - candidate_loans
        - other_loans
        - candidate_loan_repayments
        - other_loan_repayments
        - debts_owed_by
        - total_individual_contributions
        - office_state
        - district
        - special_election_status
        - primary_election_status
        - runoff_election_status
        - general_election_status
        - general_election_percent
        - pac_contributions
        - party_contributions
        - coverage_end_date
        - individual_refunds
        - committee_refunds
    - category: detail
      table: CandidateDetail
      fec_file: cn
      headers:
        - candidate_id
        - candidate_name
        - party
        - election_year
        - office_state
        - office
        - district
        - incumbent_challenger_status
        - candidate_status
        - committee_id
        - street_one
        - street_two
        - city
        - state
        - zipcode
